<#
.SYNOPSIS
    Points Qwen Code CLI and Continue.dev at the local Ollama server.
.DESCRIPTION
    Generates config for whichever aliases are actually installed, so a machine
    that only got the small models does not end up with dangling model entries.

    Writes:
      ~/.qwen/settings.json      - Qwen Code CLI (terminal agent)
      ~/.continue/config.yaml    - Continue.dev (chat + tab autocomplete)

    Existing files are backed up to *.bak-<timestamp> before being replaced.

    Cline is NOT configured here: it stores provider settings in VS Code's
    extension global state, not a file, so it must be set through its UI once.
    See docs/clients.md.
#>
[CmdletBinding()]
param(
    [string]$OllamaHost = 'http://localhost:11434',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$ollama = "$env:LOCALAPPDATA\Programs\Ollama\ollama.exe"
if (-not (Test-Path $ollama)) { $ollama = (Get-Command ollama -ErrorAction Stop).Source }

$installed = (& $ollama list) -split "`n" |
             ForEach-Object { ($_ -split '\s+')[0] } |
             Where-Object { $_ -and $_ -ne 'NAME' } |
             ForEach-Object { $_ -replace ':latest$', '' }

function Test-Model([string]$n) { return $installed -contains $n }

function Backup-IfExists([string]$path) {
    if (Test-Path $path) {
        $bak = "$path.bak-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        Copy-Item $path $bak -Force
        Write-Host "    backed up existing -> $(Split-Path $bak -Leaf)" -ForegroundColor DarkGray
    }
}

# Catalogue of aliases this repo may create, in preference order.
$catalog = @(
    @{ alias='qwen-coder'; label='Qwen3-Coder 30B-A3B (local)'; desc='MoE agentic coder, 3B active params - best for file editing and tool use' }
    @{ alias='qwen38-9b';  label='Qwen3.8 9B uncensored (local)'; desc='Uncensored, fits entirely in VRAM - fastest responses' }
    @{ alias='qwen38-27b'; label='Qwen3.8 27B uncensored (local)'; desc='Uncensored dense 28B - smartest but slow unless it fits in VRAM' }
)
$present = $catalog | Where-Object { Test-Model $_.alias }

if ($present.Count -eq 0) {
    throw 'No qwen aliases installed. Run pull-models.ps1 then create-modelfiles.ps1 first.'
}

Write-Host ''
Write-Host '  Configuring clients for:' -ForegroundColor Cyan
$present | ForEach-Object { Write-Host "    - $($_.alias)" }
Write-Host ''

# ------------------------------------------------------- Qwen Code CLI -------
# Qwen Code speaks the OpenAI protocol; Ollama exposes one at /v1. The API key is
# required by the client but ignored by Ollama, so any non-empty string works.
Write-Host '  Qwen Code CLI (~/.qwen/settings.json)' -ForegroundColor Cyan
$qwenDir = Join-Path $env:USERPROFILE '.qwen'
New-Item -ItemType Directory -Force -Path $qwenDir | Out-Null
$qwenSettings = Join-Path $qwenDir 'settings.json'
Backup-IfExists $qwenSettings

$providers = @()
foreach ($m in $present) {
    $providers += [ordered]@{
        id          = $m.alias
        name        = $m.label
        description = $m.desc
        baseUrl     = "$OllamaHost/v1"
        envKey      = 'OPENAI_API_KEY'
    }
}

$qwenConfig = [ordered]@{
    modelProviders = [ordered]@{ openai = $providers }
    env            = [ordered]@{ OPENAI_API_KEY = 'ollama' }   # placeholder; Ollama ignores it
    security       = [ordered]@{ auth = [ordered]@{ selectedType = 'openai' } }
    model          = [ordered]@{ name = $present[0].alias }
}
$qwenConfig | ConvertTo-Json -Depth 8 | Set-Content -Path $qwenSettings -Encoding UTF8
Write-Host "    wrote $qwenSettings (default model: $($present[0].alias))" -ForegroundColor Green

# ---------------------------------------------------------- Continue.dev -----
Write-Host ''
Write-Host '  Continue.dev (~/.continue/config.yaml)' -ForegroundColor Cyan
$contDir = Join-Path $env:USERPROFILE '.continue'
New-Item -ItemType Directory -Force -Path $contDir | Out-Null
$contConfig = Join-Path $contDir 'config.yaml'
Backup-IfExists $contConfig

$yaml = New-Object System.Text.StringBuilder
[void]$yaml.AppendLine('# Generated by qwen-local/scripts/configure-clients.ps1')
[void]$yaml.AppendLine('name: Local Qwen')
[void]$yaml.AppendLine('version: 1.0.0')
[void]$yaml.AppendLine('schema: v1')
[void]$yaml.AppendLine('models:')

foreach ($m in $present) {
    [void]$yaml.AppendLine("  - name: $($m.label)")
    [void]$yaml.AppendLine('    provider: ollama')
    [void]$yaml.AppendLine("    model: $($m.alias)")
    [void]$yaml.AppendLine("    apiBase: $OllamaHost")
    [void]$yaml.AppendLine('    roles:')
    [void]$yaml.AppendLine('      - chat')
    [void]$yaml.AppendLine('      - edit')
    [void]$yaml.AppendLine('      - apply')
}

# Autocomplete needs a *base* model with fill-in-the-middle training. Instruct
# models produce chatty completions and are wrong for this role.
$fim = @('qwen2.5-coder:3b-base', 'qwen2.5-coder:1.5b-base') | Where-Object { Test-Model $_ } | Select-Object -First 1
if ($fim) {
    [void]$yaml.AppendLine("  - name: Tab autocomplete")
    [void]$yaml.AppendLine('    provider: ollama')
    [void]$yaml.AppendLine("    model: $fim")
    [void]$yaml.AppendLine("    apiBase: $OllamaHost")
    [void]$yaml.AppendLine('    roles:')
    [void]$yaml.AppendLine('      - autocomplete')
    [void]$yaml.AppendLine('    autocompleteOptions:')
    [void]$yaml.AppendLine('      debounceDelay: 350')
    [void]$yaml.AppendLine('      maxPromptTokens: 1024')
    [void]$yaml.AppendLine('    defaultCompletionOptions:')
    [void]$yaml.AppendLine('      temperature: 0.1')
} else {
    [void]$yaml.AppendLine('# No FIM base model installed - tab autocomplete disabled.')
    [void]$yaml.AppendLine('# Fix: ollama pull qwen2.5-coder:1.5b-base, then re-run this script.')
}

Set-Content -Path $contConfig -Value $yaml.ToString() -Encoding UTF8
Write-Host "    wrote $contConfig" -ForegroundColor Green
if ($fim) { Write-Host "    autocomplete model: $fim" -ForegroundColor Green }

# ------------------------------------------------------------------ Cline ----
Write-Host ''
Write-Host '  Cline - manual, one time (settings are in VS Code extension state):' -ForegroundColor Yellow
Write-Host '    1. Open the Cline sidebar in VS Code'
Write-Host '    2. Settings (gear) -> API Provider -> Ollama'
Write-Host "    3. Base URL: $OllamaHost"
Write-Host "    4. Model ID: $($present[0].alias)"
Write-Host ''
Write-Host '  Done.' -ForegroundColor Green
