<#
.SYNOPSIS
    Creates short, tuned aliases for whichever Qwen models are installed.
.DESCRIPTION
    Raw Hugging Face refs like
      hf.co/mradermacher/Qwen3.8-9B-heretic-uncensored-GGUF:Q4_K_M
    are miserable to type and to put in config files. This wraps each installed
    base model in a stable alias with sampling parameters and a context length
    that suit the model family.

    Aliases created (only for models actually present):
      qwen-coder   -> qwen3-coder:30b            (MoE agentic workhorse)
      qwen38-9b    -> Qwen3.8-9B uncensored      (fits fully in VRAM)
      qwen38-27b   -> Qwen3.8-27B uncensored     (dense, hybrid offload)

    Re-running is safe - `ollama create` overwrites the alias in place and does
    not re-download anything.
#>
[CmdletBinding()]
param(
    # Context length for the big dense model. Raise on machines with more VRAM.
    [int]$DenseContext = 16384,
    # MoE models stream experts from RAM, so context is cheap for them.
    [int]$MoeContext   = 32768,
    # Context for models meant to sit ENTIRELY in VRAM. Keep this conservative:
    # on Windows, overshooting VRAM does not fail - the WDDM driver silently pages
    # over PCIe and throughput drops ~200x while `ollama ps` still says "100% GPU".
    # Measured on an 8 GB RTX 2060S: 8192->43 tok/s, 16384->40 tok/s, 24576->0.2 tok/s.
    [int]$VramFitContext = 16384
)

$ErrorActionPreference = 'Stop'

$ollama = "$env:LOCALAPPDATA\Programs\Ollama\ollama.exe"
if (-not (Test-Path $ollama)) {
    $c = Get-Command ollama -ErrorAction Ignore
    if ($c) { $ollama = $c.Source } else { throw "ollama.exe not found. Run install.ps1 first." }
}

$installed = (& $ollama list) -split "`n" | ForEach-Object { ($_ -split '\s+')[0] } | Where-Object { $_ -and $_ -ne 'NAME' }

# Qwen's published sampling recommendations for the Qwen3 family. Greedy decoding
# on these models causes repetition loops, so temperature stays > 0.
$commonParams = @'
PARAMETER temperature 0.7
PARAMETER top_p 0.8
PARAMETER top_k 20
PARAMETER repeat_penalty 1.05
'@

$aliases = @(
    @{
        alias = 'qwen-coder'
        base  = 'qwen3-coder:30b'
        ctx   = $MoeContext
        desc  = 'MoE agentic coder, 3B active params'
    }
    @{
        alias = 'qwen38-9b'
        base  = 'hf.co/mradermacher/Qwen3.8-9B-heretic-uncensored-GGUF:Q4_K_M'
        ctx   = $VramFitContext
        desc  = 'Qwen3.8 9B uncensored, sized to stay entirely in VRAM'
    }
    @{
        alias = 'qwen38-27b'
        base  = 'hf.co/JonathanColetti/Qwen3.8-27B-Uncensored-GGUF:noMTP-Q4_K_M'
        ctx   = $DenseContext
        desc  = 'Qwen3.8 27B uncensored, dense - slow if it spills out of VRAM'
    }
)

$tmpDir = Join-Path $env:TEMP 'qwen-modelfiles'
New-Item -ItemType Directory -Force -Path $tmpDir | Out-Null

foreach ($a in $aliases) {
    if ($installed -notcontains $a.base) {
        Write-Host ("  skip  {0,-12} - base not installed ({1})" -f $a.alias, $a.base) -ForegroundColor DarkGray
        continue
    }

    $content = @"
# $($a.desc)
# Generated by create-modelfiles.ps1 - edit the script, not this file.
FROM $($a.base)

PARAMETER num_ctx $($a.ctx)
$commonParams
"@

    $mf = Join-Path $tmpDir "$($a.alias).Modelfile"
    Set-Content -Path $mf -Value $content -Encoding UTF8

    Write-Host ("  build {0,-12} <- {1}" -f $a.alias, $a.base) -ForegroundColor Cyan
    & $ollama create $a.alias -f $mf 2>&1 | Where-Object { $_ -match 'error|success' } | ForEach-Object { "        $_" }
    if ($LASTEXITCODE -ne 0) { Write-Warning "failed to create $($a.alias)" }
}

Write-Host ""
Write-Host "  Aliases now available:" -ForegroundColor Green
(& $ollama list) -split "`n" | Where-Object { $_ -match '^(qwen-coder|qwen38-|NAME)' } | ForEach-Object { "    $_" }
